repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.6.3
    hooks:
      - id: isort
        additional_dependencies: [toml]
        name: isort (python)
      - id: isort
        name: isort (cython)
        additional_dependencies: [toml]
        types: [cython]
      - id: isort
        name: isort (pyi)
        additional_dependencies: [toml]
        types: [pyi]


  - repo: https://github.com/psf/black
    rev: stable
    hooks:
        - id: black
          name: black
          stages: [commit]
          language_version: python3.7

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: mixed-line-ending
    -   id: pretty-format-json
        args: [--autofix]
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
        exclude: ^tests/
